### ISSUE TITLE
App crashes constantly

### ISSUE THREAD

**Issue by Silverhawk85** [chvp/NanoLedger#65] opened 2023-12-17 09:39 UTC
The App crashes instantly when I want to open it. There are no error reports.
This happens since version 0.1.3

##### Reproduction steps

Install Nanoleger 0.1.4
Open
Instantcrash

##### Expected behaviour

App doesnt crash

##### System information

Samsung Galaxy A6+
Android 10

**Comment by chvp** [comment] 2023-12-17 09:59
Just to be clear, this didn't happen on 0.1.2 but does from 0.1.3 onwards?

**Comment by Silverhawk85** [comment] 2023-12-17 10:04
> Just to be clear, this didn't happen on 0.1.2 but does from 0.1.3 onwards?

0.1.2 works. 0.1.3 and 0.1.4 not.
I can't say what the issue is.
There is no error report.

**Comment by chvp** [comment] 2023-12-17 10:28
Unfortunately I can't reproduce this on an emulator running Android 10. Can you try clearing data and seeing if that fixes the issue?

**Comment by chvp** [comment] 2023-12-17 10:33
Or could you try running [https://f-droid.org/en/packages/com.f0x1d.logfox/](LogFox)? You should be able to find the logs for the crash that way.

**Comment by Silverhawk85** [comment] 2023-12-17 10:43
Uninstalling andreinstalling doesn't work.

I'll report back for the logs when I'm at home today. ;)

**Comment by Silverhawk85** [comment] 2023-12-18 05:22
Sorry for the late reply.
I had some problems running LogFox. Im stuck with the setup. Even when I restart the device the setup screen appears which sais that after a restart the logs should be available.
So I activated the developer fuction on my device and found an entry "bug report".
Now I have a zip-file with many files and folders in it named dumpstate but I dont know if this is of any help. I have to look into it.

**Comment by Silverhawk85** [comment] 2023-12-18 16:21
I sent you the dumpstate.txt file to your e-mail. Maybe you can find the problem. :)

**Comment by chvp** [comment] 2023-12-18 16:35
I found the relevant part of the logs:
```
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime: Process: be.chvp.nanoledger, PID: 12507
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider me.zhanghai.android.files.file.FileProvider from ProcessRecord{de31995 12507:be.chvp.nanoledger/u0a1219} (pid=12507, uid=11219) that is not exported from UID 10935
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.os.Parcel.createException(Parcel.java:2088)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.os.Parcel.readException(Parcel.java:2056)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.os.Parcel.readException(Parcel.java:2004)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5759)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.app.ActivityThread.acquireProvider(ActivityThread.java:7035)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2893)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2124)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1678)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1510)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.content.ContentResolver.openInputStream(ContentResolver.java:1194)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at x2.e.b(Unknown Source:75)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at a3.l.g(Unknown Source:59)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at r3.a.c(Unknown Source:8)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at g4.g0.run(Unknown Source:109)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at kotlinx.coroutines.internal.f.run(Unknown Source:12)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at kotlinx.coroutines.scheduling.a.run(Unknown Source:76)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  Suppressed: g4.e0: [n1{Cancelling}@74002b8, Dispatchers.IO]
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8414)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8141)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:8771)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2409)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime:  at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3347)
12-17 11:39:48.674 11219 12507 12558 E AndroidRuntime: 
```

**Comment by chvp** [comment] 2023-12-18 16:36
Not sure what is happening here, I'll take a look when I find some time (although it will probably be on the weekend).

**Comment by chvp** [comment] 2023-12-26 16:32
I still can't reproduce this, even with the Material Files app installed (which is the app mentioned in the crash). Do you have any apps installed that could mess with file access for apps?

**Comment by Silverhawk85** [comment] 2023-12-27 05:17
Today I reinstalled version 0.1.4 and suddenly it works.
In the meantime, Samsung has rolled out new updates for my smartphone. But I can't say exactly what kind of updates they were and if it works now because of the updates.

**Comment by chvp** [comment] 2023-12-27 09:45
OK, in that case I will close this issue. Feel free to re-open if you encounter it again.

**Closed by chvp** 2023-12-27 09:45 UTC
Labels: bug
